/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/puzzles/{puzzleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a puzzle by id.
         * @description Returns the full puzzle document — every cell and clue. The response
         *     is self-contained: a client with the document can render the grid and
         *     the clue list without further round-trips.
         */
        get: operations["getPuzzle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: uuid
         * @description UUID v7 string. Per ADR-0003 §6, ids are never integers.
         * @example 0190e3a4-7a2c-7c9e-8f1a-9b2d3e4f5a6b
         */
        PuzzleId: string;
        /** @description A complete mots-fléchés puzzle ready to render and play. */
        Puzzle: {
            id: components["schemas"]["PuzzleId"];
            /**
             * @description Human-facing puzzle title.
             * @example Petite grille du mardi
             */
            title: string;
            /**
             * @description BCP-47 tag (e.g. `fr`, `fr-CA`). Drives clue language and casing
             *     rules. v1 targets French mots-fléchés; the wire shape is
             *     language-neutral.
             * @example fr
             */
            language: string;
            /**
             * @description Number of columns.
             * @example 5
             */
            width: number;
            /**
             * @description Number of rows.
             * @example 5
             */
            height: number;
            /**
             * @description Cells in row-major order. Length is **at least** `width * height`;
             *     may exceed it when a cell position holds two stacked
             *     `DefinitionCell` entries (an across clue and a down clue at the
             *     same position). Clients should look up a cell by `position.row` /
             *     `position.column`, NOT by flat index `row * width + column` —
             *     that index is correct only when there are no stacked clue cells.
             */
            cells: components["schemas"]["Cell"][];
            /**
             * @description All clues, listed once. Mots-fléchés renders clue text inside a
             *     `definition` cell, but `Clue` stays separate so consumers can
             *     build a side panel, search, or tally completion without walking
             *     the cell array.
             */
            clues: components["schemas"]["Clue"][];
            /**
             * Format: date-time
             * @description ISO-8601 instant with timezone offset.
             * @example 2026-04-24T15:30:00Z
             */
            createdAt: string;
        };
        /**
         * @description Grid cell variant. `kind` discriminates: `letter` (answer cell,
         *     optionally pre-filled), `definition` (clue cell with arrow direction),
         *     `block` (unfillable decorative cell).
         */
        Cell: {
            kind: components["schemas"]["CellKind"];
            position: components["schemas"]["Position"];
        } & (components["schemas"]["LetterCell"] | components["schemas"]["DefinitionCell"] | components["schemas"]["BlockCell"]);
        /**
         * @description Discriminator for the `Cell` variants.
         * @enum {string}
         */
        CellKind: "letter" | "definition" | "block";
        /** @description Answer cell, optionally pre-filled. */
        LetterCell: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "letter";
            position: components["schemas"]["Position"];
            /**
             * @description Uppercase A-Z if pre-filled; absent or `null` for a blank cell.
             *     `null` and absence are distinct: `null` = explicitly empty in the
             *     canonical solution; absence = no constraint declared.
             */
            letter?: string | null;
        };
        /**
         * @description Mots-fléchés definition cell. Holds the clue text and an arrow
         *     showing where the answer flows.
         */
        DefinitionCell: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "definition";
            position: components["schemas"]["Position"];
            clueId: components["schemas"]["ClueId"];
            /**
             * @description Clue text rendered inside the cell.
             * @example Capitale de la France
             */
            text: string;
            arrow: components["schemas"]["Arrow"];
        };
        /** @description Unfillable decorative cell. */
        BlockCell: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "block";
            position: components["schemas"]["Position"];
        };
        /**
         * @description Arrow direction on a definition cell. `right` and `down` are the
         *     standard mots-fléchés conventions. `down-right` (first-column clue,
         *     word starts below going right) and `right-down` (first-row clue,
         *     word starts right going down) enable edge-cell interlocking.
         * @enum {string}
         */
        Arrow: "right" | "down" | "down-right" | "right-down";
        /**
         * @description Direction a clue's answer is written.
         * @enum {string}
         */
        Direction: "across" | "down";
        /** @description Zero-indexed grid coordinate. */
        Position: {
            /** @description Zero-indexed row, top to bottom. */
            row: number;
            /** @description Zero-indexed column, left to right. */
            column: number;
        };
        /**
         * Format: uuid
         * @description UUID v7 identifier of a clue.
         * @example 0190e3a4-7a2c-7c9e-8f1a-9b2d3e4f5a6c
         */
        ClueId: string;
        /**
         * @description A single clue. Mots-fléchés shows the text inside a `DefinitionCell`,
         *     but the wire keeps `Clue` separate so consumers can list, search,
         *     and tally without walking the cell array.
         */
        Clue: {
            id: components["schemas"]["ClueId"];
            direction: components["schemas"]["Direction"];
            /**
             * @description First answer cell (not the definition cell). The definition cell
             *     sits adjacent to `start` opposite `direction`.
             */
            start: components["schemas"]["Position"];
            /** @description Number of letter cells in the answer. */
            length: number;
            /**
             * @description Clue text. Duplicated from `DefinitionCell.text` on purpose —
             *     cheap on a 225-cell grid and spares clients a join.
             */
            text: string;
        };
        /**
         * @description RFC 7807 error envelope (ADR-0003 §6). Additional members per
         *     RFC 7807 §3.2 may appear; clients tolerate them.
         */
        Problem: {
            /**
             * Format: uri
             * @description Stable URI for the error class. Clients route on `type`, never on
             *     `title` or `detail`.
             * @example https://bliss.example/errors/puzzle-not-found
             */
            type: string;
            /**
             * @description Short, human-readable summary of the error class.
             * @example Puzzle not found
             */
            title: string;
            /**
             * @description HTTP status code, repeated for clients that lose it.
             * @example 404
             */
            status: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri-reference
             * @description URI reference identifying the specific occurrence.
             */
            instance?: string;
        };
    };
    responses: never;
    parameters: {
        /** @description UUID v7 identifier of the puzzle. */
        PuzzleId: components["schemas"]["PuzzleId"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPuzzle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID v7 identifier of the puzzle. */
                puzzleId: components["parameters"]["PuzzleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Puzzle found. Canonical sample at
             *     `grid/api/examples/get-puzzle-200.json` is the contract-test
             *     fixture for both sides of the wire.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Puzzle"];
                };
            };
            /**
             * @description Path parameter `puzzleId` is not a valid UUID. RFC 7807 body;
             *     `type` is `https://bliss.example/errors/invalid-puzzle-id`.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description Puzzle generation failed. The requested constraints (grid size,
             *     word list, interlocking rules) are unsatisfiable within the
             *     attempt budget. RFC 7807 body;
             *     `type` is `https://bliss.example/errors/puzzle-generation-failed`.
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
