/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/puzzles/{puzzleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a puzzle by id.
         * @description Returns the full puzzle document — every cell and clue. The response
         *     is self-contained: a client with the document can render the grid and
         *     the clue list without further round-trips.
         */
        get: operations["getPuzzle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/puzzles/{puzzleId}/hints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Spend a hint to check whether a word exists in the corpus.
         * @description Per-puzzle hint mechanism. The client submits a candidate word; the
         *     server reports whether it is a known lemma in the French corpus and
         *     decrements the puzzle's hint budget. Each answered lookup (200 or
         *     400/404 — anything that consumes a server-side dictionary check)
         *     costs one hint; once the budget is exhausted the server responds
         *     with 429 and the client UI SHOULD disable the affordance.
         *
         *     Framing as "hint" rather than free corpus lookup is intentional: it
         *     caps unauthenticated clients to `Puzzle.hintsAllowed` calls per
         *     puzzle and prevents the endpoint being used as a dictionary scrape.
         *     Player identity on the wire is the `X-Session-Id` header (UUID v7,
         *     same convention as `game/api`'s `SessionId`). The server keeps a
         *     per-(puzzle, session) hint counter; absent or malformed values
         *     produce a 400 `invalid-session-id` response.
         */
        post: operations["requestWordHint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/puzzles/{puzzleId}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify a filled grid against the canonical solution.
         * @description Compares submitted cells against the server's canonical solution.
         *     Returns whether the grid is solved and, if not, the positions of
         *     mismatched or unfilled cells — never the canonical letter. The
         *     response cannot be used to reconstruct the solution in a single
         *     call; brute-force letter extraction would require
         *     `O(width × height × 26)` legal calls and is mitigated by edge rate
         *     limiting (ops concern, out of scope for this schema).
         *
         *     Stateless: any client holding a `puzzleId` may call. Cleared cells
         *     are absent from the request — do NOT send `letter: null`.
         */
        post: operations["validatePuzzle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: uuid
         * @description UUID v7 string. Per ADR-0003 §6, ids are never integers.
         * @example 0190e3a4-7a2c-7c9e-8f1a-9b2d3e4f5a6b
         */
        PuzzleId: string;
        /** @description A complete mots-fléchés puzzle ready to render and play. */
        Puzzle: {
            id: components["schemas"]["PuzzleId"];
            /**
             * @description Human-facing puzzle title.
             * @example Petite grille du mardi
             */
            title: string;
            /**
             * @description BCP-47 tag (e.g. `fr`, `fr-CA`). Drives clue language and casing
             *     rules. v1 targets French mots-fléchés; the wire shape is
             *     language-neutral.
             * @example fr
             */
            language: string;
            /**
             * @description Number of columns.
             * @example 5
             */
            width: number;
            /**
             * @description Number of rows.
             * @example 5
             */
            height: number;
            /**
             * @description Cells in row-major order. Length is **at least** `width * height`;
             *     may exceed it when a cell position holds two stacked
             *     `DefinitionCell` entries (an across clue and a down clue at the
             *     same position). Clients should look up a cell by `position.row` /
             *     `position.column`, NOT by flat index `row * width + column` —
             *     that index is correct only when there are no stacked clue cells.
             */
            cells: components["schemas"]["Cell"][];
            /**
             * @description All clues, listed once. Mots-fléchés renders clue text inside a
             *     `definition` cell, but `Clue` stays separate so consumers can
             *     build a side panel, search, or tally completion without walking
             *     the cell array.
             */
            clues: components["schemas"]["Clue"][];
            /**
             * @description Hint budget for this puzzle. The client may call
             *     `POST /v1/puzzles/{puzzleId}/hints` up to this many times before
             *     the server returns 429. The budget scope (per puzzle, per player)
             *     is server-defined; the wire contract only carries the cap.
             * @example 3
             */
            hintsAllowed: number;
            /**
             * Format: date-time
             * @description ISO-8601 instant with timezone offset.
             * @example 2026-04-24T15:30:00Z
             */
            createdAt: string;
        };
        /**
         * @description Grid cell variant. `kind` discriminates: `letter` (answer cell,
         *     optionally pre-filled), `definition` (clue cell with arrow direction),
         *     `block` (unfillable decorative cell).
         */
        Cell: {
            kind: components["schemas"]["CellKind"];
            position: components["schemas"]["Position"];
        } & (components["schemas"]["LetterCell"] | components["schemas"]["DefinitionCell"] | components["schemas"]["BlockCell"]);
        /**
         * @description Discriminator for the `Cell` variants.
         * @enum {string}
         */
        CellKind: "letter" | "definition" | "block";
        /**
         * @description Player-fillable answer cell. Geometry only — the canonical solution
         *     is server-private and never appears on the wire. Distinguished from
         *     `BlockCell` by `kind`. Clients submit filled cells to
         *     `POST /v1/puzzles/{puzzleId}/validate` for verification.
         */
        LetterCell: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "letter";
            position: components["schemas"]["Position"];
        };
        /**
         * @description Mots-fléchés definition cell. Holds the clue text and an arrow
         *     showing where the answer flows.
         */
        DefinitionCell: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "definition";
            position: components["schemas"]["Position"];
            clueId: components["schemas"]["ClueId"];
            /**
             * @description Clue text rendered inside the cell.
             * @example Capitale de la France
             */
            text: string;
            arrow: components["schemas"]["Arrow"];
        };
        /** @description Unfillable decorative cell. */
        BlockCell: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "block";
            position: components["schemas"]["Position"];
        };
        /**
         * @description Arrow direction on a definition cell. `right` and `down` are the
         *     standard mots-fléchés conventions. `down-right` (first-column clue,
         *     word starts below going right) and `right-down` (first-row clue,
         *     word starts right going down) enable edge-cell interlocking.
         * @enum {string}
         */
        Arrow: "right" | "down" | "down-right" | "right-down";
        /**
         * @description Direction a clue's answer is written.
         * @enum {string}
         */
        Direction: "across" | "down";
        /** @description Zero-indexed grid coordinate. */
        Position: {
            /** @description Zero-indexed row, top to bottom. */
            row: number;
            /** @description Zero-indexed column, left to right. */
            column: number;
        };
        /**
         * Format: uuid
         * @description UUID v7 identifier of a clue.
         * @example 0190e3a4-7a2c-7c9e-8f1a-9b2d3e4f5a6c
         */
        ClueId: string;
        /**
         * @description A single clue. Mots-fléchés shows the text inside a `DefinitionCell`,
         *     but the wire keeps `Clue` separate so consumers can list, search,
         *     and tally without walking the cell array.
         */
        Clue: {
            id: components["schemas"]["ClueId"];
            direction: components["schemas"]["Direction"];
            /**
             * @description First answer cell (not the definition cell). The definition cell
             *     sits adjacent to `start` opposite `direction`.
             */
            start: components["schemas"]["Position"];
            /** @description Number of letter cells in the answer. */
            length: number;
            /**
             * @description Clue text. Duplicated from `DefinitionCell.text` on purpose —
             *     cheap on a 225-cell grid and spares clients a join.
             */
            text: string;
        };
        /** @description Request body for `POST /v1/puzzles/{puzzleId}/hints`. */
        WordHintRequest: {
            /**
             * @description Candidate French word. Server normalizes case and Unicode (NFC)
             *     before lookup; clients SHOULD send lowercase.
             * @example forêt
             */
            word: string;
        };
        /**
         * @description Response body for `POST /v1/puzzles/{puzzleId}/hints` on a 200. The
         *     server-normalized form is echoed so the client can highlight the
         *     match it actually evaluated.
         */
        WordHintResult: {
            /**
             * @description Server-normalized form (NFC, lowercase).
             * @example forêt
             */
            word: string;
            /**
             * @description True iff the word is a known lemma in the corpus.
             * @example true
             */
            exists: boolean;
            /**
             * @description Hints left after this call. `0` means the next call will return
             *     a 429 with `type` `https://bliss.example/errors/hint-budget-exhausted`.
             * @example 2
             */
            hintsRemaining: number;
        };
        /**
         * @description Request body for `POST /v1/puzzles/{puzzleId}/validate`. Carries the
         *     cells the client wants to verify. Cleared / unfilled letter cells are
         *     absent — do NOT send `letter: null`. Order is irrelevant; the server
         *     keys by `(row, column)`. Duplicate `(row, column)` entries are a 400.
         * @example {
         *       "filledCells": [
         *         {
         *           "row": 0,
         *           "column": 1,
         *           "letter": "P"
         *         },
         *         {
         *           "row": 0,
         *           "column": 3,
         *           "letter": "G"
         *         },
         *         {
         *           "row": 0,
         *           "column": 5,
         *           "letter": "S"
         *         }
         *       ]
         *     }
         */
        ValidatePuzzleRequest: {
            /**
             * @description Submitted letters. `maxItems` matches the protocol-level upper
             *     bound on letter cells in a `Puzzle` (`width × height` with
             *     `width`, `height` ≤ 50).
             */
            filledCells: components["schemas"]["FilledCell"][];
        };
        /**
         * @description A single client-submitted letter for a letter cell. `(row, column)`
         *     must point at a `letter`-kind cell in the puzzle; pointing at a
         *     definition or block cell is a 400.
         */
        FilledCell: {
            /** @example 0 */
            row: number;
            /** @example 1 */
            column: number;
            /**
             * @description Single uppercase A-Z code point. Diacritics are normalized
             *     client-side before submission.
             * @example P
             */
            letter: string;
        };
        /**
         * @description Validation outcome. The server intentionally returns positions only,
         *     never the canonical letter, so the response cannot be used to
         *     reconstruct the solution in a single call.
         */
        ValidatePuzzleResult: {
            /**
             * @description True iff every letter cell is filled and matches the canonical
             *     solution.
             * @example false
             */
            solved: boolean;
            /**
             * @description Positions where the submitted letter is wrong OR the letter cell
             *     was not filled by the client. Empty iff `solved` is true.
             * @example [
             *       {
             *         "row": 4,
             *         "column": 1
             *       },
             *       {
             *         "row": 6,
             *         "column": 9
             *       }
             *     ]
             */
            incorrectCells: components["schemas"]["Position"][];
        };
        /**
         * @description RFC 7807 error envelope (ADR-0003 §6). Additional members per
         *     RFC 7807 §3.2 may appear; clients tolerate them.
         */
        Problem: {
            /**
             * Format: uri
             * @description Stable URI for the error class. Clients route on `type`, never on
             *     `title` or `detail`.
             * @example https://bliss.example/errors/puzzle-not-found
             */
            type: string;
            /**
             * @description Short, human-readable summary of the error class.
             * @example Puzzle not found
             */
            title: string;
            /**
             * @description HTTP status code, repeated for clients that lose it.
             * @example 404
             */
            status: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri-reference
             * @description URI reference identifying the specific occurrence.
             */
            instance?: string;
        };
    };
    responses: never;
    parameters: {
        /** @description UUID v7 identifier of the puzzle. */
        PuzzleId: components["schemas"]["PuzzleId"];
        /**
         * @description UUID v7 identifying the calling player's session. The server uses
         *     this to track per-(puzzle, session) hint budgets. Absent or
         *     non-UUID values produce a 400 `invalid-session-id` response.
         */
        SessionId: string;
        /**
         * @description Number of columns to generate. Defaults to 10 when omitted, matching
         *     the historical solo-mode size. Valid range is 5..15 inclusive; values
         *     outside that range — or non-integers — produce a 400 with problem
         *     type `https://bliss.example/errors/invalid-puzzle-dimensions`. The
         *     bounds keep the CSP solver's vocabulary needs and per-request time
         *     budget reasonable.
         */
        PuzzleWidth: number;
        /**
         * @description Number of rows to generate. Defaults to 10 when omitted, matching
         *     the historical solo-mode size. Valid range is 5..15 inclusive; values
         *     outside that range — or non-integers — produce a 400 with problem
         *     type `https://bliss.example/errors/invalid-puzzle-dimensions`.
         */
        PuzzleHeight: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPuzzle: {
        parameters: {
            query?: {
                /**
                 * @description Number of columns to generate. Defaults to 10 when omitted, matching
                 *     the historical solo-mode size. Valid range is 5..15 inclusive; values
                 *     outside that range — or non-integers — produce a 400 with problem
                 *     type `https://bliss.example/errors/invalid-puzzle-dimensions`. The
                 *     bounds keep the CSP solver's vocabulary needs and per-request time
                 *     budget reasonable.
                 */
                width?: components["parameters"]["PuzzleWidth"];
                /**
                 * @description Number of rows to generate. Defaults to 10 when omitted, matching
                 *     the historical solo-mode size. Valid range is 5..15 inclusive; values
                 *     outside that range — or non-integers — produce a 400 with problem
                 *     type `https://bliss.example/errors/invalid-puzzle-dimensions`.
                 */
                height?: components["parameters"]["PuzzleHeight"];
            };
            header?: never;
            path: {
                /** @description UUID v7 identifier of the puzzle. */
                puzzleId: components["parameters"]["PuzzleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Puzzle found. Canonical sample at
             *     `grid/api/examples/get-puzzle-200.json` is the contract-test
             *     fixture for both sides of the wire. The example reflects the
             *     default 10×10 size; requesting `?width=7&height=7` produces an
             *     analogous 7×7 document with the same wire shape.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Puzzle"];
                };
            };
            /**
             * @description Request is malformed. RFC 7807 body. Variants:
             *     - Path parameter `puzzleId` is not a valid UUID
             *       (`type` = `https://bliss.example/errors/invalid-puzzle-id`).
             *     - Query parameter `width` or `height` is not an integer or is
             *       outside the supported 5..15 range
             *       (`type` = `https://bliss.example/errors/invalid-puzzle-dimensions`).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description Puzzle generation failed. The requested constraints (grid size,
             *     word list, interlocking rules) are unsatisfiable within the
             *     attempt budget. RFC 7807 body;
             *     `type` is `https://bliss.example/errors/puzzle-generation-failed`.
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    requestWordHint: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description UUID v7 identifying the calling player's session. The server uses
                 *     this to track per-(puzzle, session) hint budgets. Absent or
                 *     non-UUID values produce a 400 `invalid-session-id` response.
                 */
                "X-Session-Id": components["parameters"]["SessionId"];
            };
            path: {
                /** @description UUID v7 identifier of the puzzle. */
                puzzleId: components["parameters"]["PuzzleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WordHintRequest"];
            };
        };
        responses: {
            /**
             * @description Hint consumed. Body reports whether the word exists in the
             *     corpus and the remaining budget for this `(puzzle, player)`.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WordHintResult"];
                };
            };
            /**
             * @description Request is malformed. RFC 7807. Variants:
             *     - `X-Session-Id` absent or not a valid UUID
             *       (`type` = `https://bliss.example/errors/invalid-session-id`).
             *     - Path parameter `puzzleId` is not a valid UUID
             *       (`type` = `https://bliss.example/errors/invalid-puzzle-id`).
             *     - Request body missing or unparseable
             *       (`type` = `https://bliss.example/errors/invalid-request-body`).
             *     - `word` violates length or character class
             *       (`type` = `https://bliss.example/errors/invalid-word`).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description No puzzle with this id. RFC 7807;
             *     `type` is `https://bliss.example/errors/puzzle-not-found`.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description Hint budget exhausted for this `(puzzle, player)`. RFC 7807;
             *     `type` is `https://bliss.example/errors/hint-budget-exhausted`.
             *     The body's `detail` SHOULD echo `hintsRemaining: 0`.
             */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    validatePuzzle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID v7 identifier of the puzzle. */
                puzzleId: components["parameters"]["PuzzleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidatePuzzleRequest"];
            };
        };
        responses: {
            /**
             * @description Validation completed. `incorrectCells` is empty iff `solved` is
             *     true. Cells the client did not fill appear in `incorrectCells`
             *     alongside cells whose submitted letter is wrong.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidatePuzzleResult"];
                };
            };
            /**
             * @description Request invalid: position out of range, position pointing at a
             *     non-letter cell, `letter` not a single uppercase A-Z, or
             *     duplicate `(row, column)`. RFC 7807;
             *     `type` is `https://bliss.example/errors/invalid-validate-request`.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description No puzzle with this id. RFC 7807;
             *     `type` is `https://bliss.example/errors/puzzle-not-found`.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
