/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/lobbies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new lobby.
         * @description Creates a new lobby in WAITING with the calling player as the sole
         *     member and owner. The client supplies `ownerSessionId` (UUID v7,
         *     generated client-side per ADR-0018 §"sessions") and `ownerPseudonym`.
         *     The server mints `lobbyId` (base58 nanoid, ADR-0020) and returns the
         *     full `Lobby` resource.
         *
         *     The 201 response includes a `Location` header pointing at the
         *     canonical read URL.
         */
        post: operations["createLobby"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lobbies/{lobbyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read current lobby state.
         * @description Returns the full `Lobby` snapshot. Used by the frontend route loader
         *     to bootstrap the WebSocket connection: the WS opens AFTER the loader
         *     confirms the lobby exists and learns the current lifecycle state.
         */
        get: operations["getLobby"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 8-char base58 nanoid (URL-safe; no `0`, `O`, `I`, `l`). Documented
         *     exception to ADR-0003 §6's UUID v7 default per ADR-0020 — lobbies
         *     embed their id in human-shareable URLs, where 36-char UUIDs are
         *     unwieldy. Mirrors `LobbyId` in `game/api/asyncapi.yaml`; keep in sync.
         * @example 7gQ2xK9p
         */
        LobbyId: string;
        /**
         * Format: uuid
         * @description UUID v7 string per ADR-0003 §6. Generated client-side on first visit
         *     and persisted in `localStorage`. Mirrors `SessionId` in
         *     `game/api/asyncapi.yaml`; keep in sync.
         * @example 0190e3a4-7a2c-7c9e-8f1a-9b2d3e4f5a6b
         */
        SessionId: string;
        /**
         * @description Player display name. Not unique within a lobby. Leading / trailing
         *     whitespace is rejected. Mirrors `Pseudonym` in
         *     `game/api/asyncapi.yaml`; keep in sync.
         * @example Joueur 1234
         */
        Pseudonym: string;
        /**
         * Format: date-time
         * @description ISO-8601 instant with timezone offset (ADR-0003 §6).
         * @example 2026-05-02T15:30:00Z
         */
        Instant: string;
        /**
         * @description Lobby lifecycle (ADR-0018). Mirrors `LobbyLifecycleState` in `game/api/asyncapi.yaml`.
         * @enum {string}
         */
        LobbyLifecycleState: "WAITING" | "IN_PROGRESS" | "COMPLETED";
        /**
         * @description Dimensions chosen by the lobby owner before start. Mirrors `GridConfig`
         *     in `game/api/asyncapi.yaml`; keep in sync.
         */
        GridConfig: {
            /**
             * @description Number of columns.
             * @example 7
             */
            width: number;
            /**
             * @description Number of rows.
             * @example 7
             */
            height: number;
        };
        /**
         * @description A player currently holding a slot in the lobby. Mirrors `Player` in
         *     `game/api/asyncapi.yaml`; keep in sync.
         */
        Player: {
            sessionId: components["schemas"]["SessionId"];
            pseudonym: components["schemas"]["Pseudonym"];
            joinedAt: components["schemas"]["Instant"];
        };
        /**
         * @description Game-context projection of a puzzle. Carries every field a client
         *     needs to render and play. Owned by game/ — not a $ref into grid/
         *     (ADR-0001 §1 forbids cross-context file dependencies). The server
         *     fetches from grid/ on startGame and forwards the document verbatim.
         *     Mirrors `GamePuzzle` in `game/api/asyncapi.yaml`; keep in sync.
         */
        GamePuzzle: {
            /**
             * Format: uuid
             * @description UUID v7 puzzle identifier.
             * @example 0190e3a4-7a2c-7c9e-8f1a-9b2d3e4f5a6c
             */
            id: string;
            /** @example Petite grille du mardi */
            title: string;
            /**
             * @description BCP-47 tag.
             * @example fr
             */
            language: string;
            /**
             * @description Number of columns.
             * @example 5
             */
            width: number;
            /**
             * @description Number of rows.
             * @example 5
             */
            height: number;
            /** @description Cells in row-major order; look up by position.row/position.column. */
            cells: components["schemas"]["GameCell"][];
            clues: components["schemas"]["GameClue"][];
            /**
             * @description Hint budget for this puzzle. Mirrors `Puzzle.hintsAllowed` in
             *     `grid/api/openapi.yaml`; forwarded verbatim from grid/ on startGame.
             * @example 3
             */
            hintsAllowed: number;
            createdAt: components["schemas"]["Instant"];
        };
        /**
         * @description Grid cell. `kind` discriminates letter / definition / block. Mirrors
         *     `GameCell` in `game/api/asyncapi.yaml`; keep in sync.
         */
        GameCell: {
            kind: components["schemas"]["GameCellKind"];
            position: components["schemas"]["GamePosition"];
        } & (components["schemas"]["GameLetterCell"] | components["schemas"]["GameDefinitionCell"] | components["schemas"]["GameBlockCell"]);
        /**
         * @description Discriminator for `GameCell` variants.
         * @enum {string}
         */
        GameCellKind: "letter" | "definition" | "block";
        /**
         * @description Player-fillable answer cell. The canonical solution is server-private
         *     and never carried on the wire. Player input flows in via the
         *     `cellUpdate` WebSocket frame and is rebroadcast as `cellUpdated`. On
         *     solve, `gameSolved.finalEntries` carries the full solved grid — the
         *     only post-completion broadcast of canonical letters. Mirrors
         *     `GameLetterCell` in `game/api/asyncapi.yaml`; keep in sync per
         *     ADR-0001 §1 (no cross-context $ref).
         */
        GameLetterCell: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "letter";
            position: components["schemas"]["GamePosition"];
        };
        /**
         * @description Mots-fleches definition cell. Carries 1 clue (the common case) or 2
         *     clues (the corner-cell idiom — an across clue and a down clue stacked
         *     at one position). Mirrors `GameDefinitionCell` in
         *     `game/api/asyncapi.yaml`; keep in sync.
         */
        GameDefinitionCell: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "definition";
            position: components["schemas"]["GamePosition"];
            clues: components["schemas"]["GameDefinitionClue"][];
        };
        /** @description A single clue carried by a `GameDefinitionCell`. */
        GameDefinitionClue: {
            /**
             * Format: uuid
             * @description UUID v7 clue identifier.
             * @example 0190e3a4-7a2c-7c9e-8f1a-9b2d3e4f5a6d
             */
            id: string;
            /** @example Capitale de la France */
            text: string;
            arrow: components["schemas"]["GameArrow"];
        };
        /** @description Unfillable decorative cell. */
        GameBlockCell: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "block";
            position: components["schemas"]["GamePosition"];
        };
        /**
         * @description Arrow direction on a mots-fleches definition cell.
         * @enum {string}
         */
        GameArrow: "right" | "down" | "down-right" | "right-down";
        /** @description Zero-indexed grid coordinate. */
        GamePosition: {
            /** @description Zero-indexed row, top to bottom. */
            row: number;
            /** @description Zero-indexed column, left to right. */
            column: number;
        };
        /** @description A single clue listed in `GamePuzzle.clues`. */
        GameClue: {
            /**
             * Format: uuid
             * @description UUID v7 clue identifier.
             * @example 0190e3a4-7a2c-7c9e-8f1a-9b2d3e4f5a6e
             */
            id: string;
            direction: components["schemas"]["GameClueDirection"];
            start: components["schemas"]["GamePosition"];
            /** @description Number of letter cells in the answer. */
            length: number;
            text: string;
        };
        /**
         * @description Direction a clue's answer is written.
         * @enum {string}
         */
        GameClueDirection: "across" | "down";
        /**
         * @description Active game embedded in `Lobby.game` while IN_PROGRESS or COMPLETED.
         *     `completedAt` is in `required` because the field is always present on
         *     the wire — `null` (still in progress) and a timestamp (solved) are
         *     both meaningful values. `entries` carries every letter typed so far
         *     (server-authoritative) so a client refreshing the page in mid-game
         *     rehydrates the grid from the REST snapshot before the WebSocket
         *     opens. Cleared cells are absent from the list; entries are sorted
         *     by row then column for stable rendering. `lockedPositions` mirrors
         *     the cumulative server-locked cells (every word validated correct
         *     so far) so the same refresh path renders read-only cells without
         *     waiting for a WebSocket replay; always emitted (empty list when
         *     no word has been locked). `presence` is the ephemeral cursor map
         *     for currently-connected players; optional and absent or empty
         *     when state is WAITING/COMPLETED. Mirrors `GameSession` in
         *     `game/api/asyncapi.yaml`; keep in sync.
         */
        GameSession: {
            puzzle: components["schemas"]["GamePuzzle"];
            /** @description Every cell typed so far. Empty list when no player has typed yet. */
            entries: components["schemas"]["CellEntry"][];
            /**
             * @description Cumulative cells locked by server-side word validation. Order is
             *     row then column for diff-friendly snapshots. Empty list when no
             *     word has been locked.
             */
            lockedPositions: components["schemas"]["GamePosition"][];
            startedAt: components["schemas"]["Instant"];
            /** @description Set once the lobby reaches COMPLETED; `null` while IN_PROGRESS. */
            completedAt: components["schemas"]["Instant"] | null;
            /**
             * @description Ephemeral cursor positions of currently-connected players.
             *     Empty or absent when state is WAITING/COMPLETED. Not persisted
             *     (lives in `SessionManager`'s in-memory map per ADR-0018 §3).
             *     Mirrors `lobbyState.game.presence` on the WebSocket snapshot.
             */
            presence?: components["schemas"]["PresenceEntry"][];
        };
        /**
         * @description A single placed letter in the canonical entries list. Used by
         *     `GameSession.entries` to rehydrate a refreshing client's grid.
         *     `letter` is always non-null — cleared cells are absent from the
         *     list. `sessionId` and `writtenAt` mirror the per-cell `cellUpdated`
         *     WebSocket event so a future per-author UI tint can colour each
         *     entry. Mirrors `CellEntry` in `game/api/asyncapi.yaml`; keep in sync.
         */
        CellEntry: {
            sessionId: components["schemas"]["SessionId"];
            /** @example 0 */
            row: number;
            /** @example 3 */
            column: number;
            /**
             * @description Always non-null. Cleared cells are absent from the list.
             * @example P
             */
            letter: string;
            writtenAt: components["schemas"]["Instant"];
        };
        /**
         * @description Ephemeral cursor position of one currently-connected player. Carried
         *     by `GameSession.presence` so a client bootstrapping via REST sees
         *     peer cursors immediately, before opening the WebSocket. `row`,
         *     `column`, `direction` are all nullable — `null` means the player
         *     has no cell focused. Absence from the list means the player is not
         *     connected; per ADR-0003 §6, absence and `null` are distinct.
         *     Carries no domain meaning; not persisted. Mirrors `PresenceEntry`
         *     in `game/api/asyncapi.yaml`; keep in sync.
         */
        PresenceEntry: {
            sessionId: components["schemas"]["SessionId"];
            /**
             * @description Zero-indexed row of the focused cell; `null` when no cell is focused.
             * @example 0
             */
            row: number | null;
            /**
             * @description Zero-indexed column of the focused cell; `null` when no cell is focused.
             * @example 3
             */
            column: number | null;
            /** @description Direction the player is currently solving; `null` when no cell is focused. Lets peers tint the whole word. */
            direction: components["schemas"]["GameClueDirection"] | null;
        };
        /**
         * @description Full lobby snapshot. `game` is in `required` because the field is
         *     always present on the wire — `null` (state == WAITING) and a populated
         *     `GameSession` (state in {IN_PROGRESS, COMPLETED}) are both meaningful.
         *     ADR-0003 §6: absence and `null` are distinct.
         */
        Lobby: {
            id: components["schemas"]["LobbyId"];
            ownerSessionId: components["schemas"]["SessionId"];
            /**
             * @description Up to 8 players (ADR-0018). Wire shape is an array, NOT a
             *     map-keyed-by-sessionId — JSON object keys are unordered, an array
             *     preserves join order for stable rendering.
             */
            players: components["schemas"]["Player"][];
            state: components["schemas"]["LobbyLifecycleState"];
            gridConfig: components["schemas"]["GridConfig"];
            /** @description Null while WAITING; populated while IN_PROGRESS or COMPLETED. */
            game: components["schemas"]["GameSession"] | null;
            /**
             * @description Human-friendly join code surfaced to non-owner players (the
             *     Accueil "Rejoindre avec un code" flow renders this in the
             *     input). Six uppercase alphanumeric characters, drawn from the
             *     unambiguous Crockford-style alphabet (no `0`/`O`, `1`/`I`,
             *     `L`) so a player reading the code aloud cannot land on a
             *     different lobby. Null until the join-by-code feature ships
             *     its mint logic in a follow-up PR; clients should fall back
             *     to the existing URL-share path while absent.
             * @example A2B3C4
             */
            code?: string | null;
        };
        /**
         * @description Request body for `POST /v1/lobbies`.
         * @example {
         *       "ownerSessionId": "0190e3a4-7a2c-7c9e-8f1a-9b2d3e4f5a6b",
         *       "ownerPseudonym": "Joueur 1234"
         *     }
         */
        CreateLobbyRequest: {
            ownerSessionId: components["schemas"]["SessionId"];
            ownerPseudonym: components["schemas"]["Pseudonym"];
        };
        /**
         * @description RFC 7807 error envelope (ADR-0003 §6). Additional members per
         *     RFC 7807 §3.2 may appear; clients tolerate them.
         */
        Problem: {
            /**
             * Format: uri
             * @description Stable URI for the error class. Clients route on `type`, never on
             *     `title` or `detail`.
             * @example https://bliss.example/errors/lobby-not-found
             */
            type: string;
            /**
             * @description Short, human-readable summary of the error class.
             * @example Lobby not found
             */
            title: string;
            /**
             * @description HTTP status code, repeated for clients that lose it.
             * @example 404
             */
            status: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri-reference
             * @description URI reference identifying the specific occurrence.
             */
            instance?: string;
        };
    };
    responses: never;
    parameters: {
        /** @description 8-char base58 nanoid identifying the lobby (ADR-0020). */
        LobbyIdPath: components["schemas"]["LobbyId"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createLobby: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLobbyRequest"];
            };
        };
        responses: {
            /** @description Lobby created. Body is the freshly-minted `Lobby` resource. */
            201: {
                headers: {
                    /** @description Canonical read URL of the new lobby. */
                    Location: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lobby"];
                };
            };
            /**
             * @description Request body is malformed. RFC 7807. Variants:
             *     - `ownerSessionId` is not a UUID v7
             *       (`type` = `https://bliss.example/errors/invalid-lobby-create-request`).
             *     - `ownerPseudonym` violates length / whitespace rules
             *       (same `type`).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getLobby: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 8-char base58 nanoid identifying the lobby (ADR-0020). */
                lobbyId: components["parameters"]["LobbyIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lobby found. Body is the current `Lobby` snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lobby"];
                };
            };
            /**
             * @description Path parameter `lobbyId` does not match the base58 nanoid pattern.
             *     RFC 7807; `type` is `https://bliss.example/errors/invalid-lobby-id`.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description No lobby exists for the supplied id. The lobby may have never
             *     existed, or it may have been garbage-collected after the last
             *     player left (ADR-0018 §3 — in-memory v1, no durable storage).
             *     RFC 7807; `type` is `https://bliss.example/errors/lobby-not-found`.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
