#!/usr/bin/env python3
"""Merge surface_clues.csv into the runtime words-fr.csv consumed by the API.

For each row in words-fr.csv whose surface (word column) has a clue in
surface_clues.csv (validator-ok and filter_score >= threshold), replace
the placeholder `clue` field. Other rows keep the placeholder
(clue == word) so generation still works.

Source/license columns describe the WORD provenance (grammalecte
morphology — MPL-2.0); the clue text itself is LoRA-generated by us
from CC0 training data, no DBnary. We preserve the existing source
and source_license fields and don't add per-field provenance.
"""
from __future__ import annotations
import argparse, csv, shutil
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--wordlist", type=Path,
                   default=REPO / "grid/api/src/main/resources/words/words-fr.csv")
    p.add_argument("--shipped", type=Path,
                   default=REPO / "data/eval/production/surface_clues.csv")
    p.add_argument("--dropped", type=Path,
                   default=REPO / "data/eval/production/surface_clues_dropped.csv")
    p.add_argument("--include-dropped", action="store_true",
                   help="also use lower-confidence (dropped) surface clues")
    p.add_argument("--min-score", type=float, default=0.0,
                   help="minimum filter_score; clues below are skipped")
    p.add_argument("--backup", type=Path,
                   default=REPO / "/tmp/words-fr.backup.csv")
    args = p.parse_args()

    def keep(r: dict) -> bool:
        try:
            return float(r.get("filter_score", 0) or 0) >= args.min_score
        except ValueError:
            return False

    # surface_lower -> (clue_text, compact_bool_str)
    surface_clue: dict[str, tuple[str, str]] = {}
    with args.shipped.open(encoding="utf-8", newline="") as f:
        for r in csv.DictReader(f):
            if keep(r):
                surface_clue[r["surface"].lower()] = (
                    r["clue"], r.get("compact", "false")
                )
    if args.include_dropped:
        with args.dropped.open(encoding="utf-8", newline="") as f:
            for r in csv.DictReader(f):
                if keep(r):
                    surface_clue.setdefault(
                        r["surface"].lower(),
                        (r["clue"], r.get("compact", "false")),
                    )
    print(f"surface clues available (score >= {args.min_score}): {len(surface_clue)}")

    # Backup, then rewrite in place.
    shutil.copy2(args.wordlist, args.backup)
    with args.wordlist.open(encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))
        fieldnames = list(rows[0].keys())

    # Add `compact` column if missing. All curated short-fr / fr / roman2
    # entries are stamped compact=true (≤ 3 chars always fits the stacked
    # half-cell at any reasonable font size).
    if "compact" not in fieldnames:
        fieldnames.append("compact")
        for r in rows:
            r["compact"] = "true"

    updated = 0
    for r in rows:
        word = r.get("word", "").strip().lower()
        entry = surface_clue.get(word)
        if entry:
            clue, compact = entry
            r["clue"] = clue
            r["compact"] = compact
            updated += 1

    with args.wordlist.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, lineterminator="\n")
        w.writeheader()
        for r in rows:
            w.writerow({k: r.get(k, "") for k in fieldnames})

    pct = updated / len(rows) * 100
    print(f"updated {updated}/{len(rows)} rows ({pct:.1f}%)")
    print(f"backup: {args.backup}")


if __name__ == "__main__":
    main()
