package com.bliss.grid.api.infrastructure.words

import com.bliss.grid.domain.generation.WordRepository
import com.bliss.grid.domain.model.Word
import org.apache.commons.csv.CSVFormat
import org.apache.commons.csv.CSVParser
import org.apache.commons.csv.CSVRecord
import java.io.InputStreamReader
import java.nio.charset.StandardCharsets

/**
 * Classpath-backed [WordRepository] reading the committed CSV corpus
 * (ADR-0013 §8 — CSV as source of truth).
 *
 * Production grid-api ships its words as
 * `grid/api/src/main/resources/words/words-<lang>.csv`, generated by the
 * worker's `export-words` sub-command from the local-dev `words` table after
 * an operator review pass. The CSV is the single source of truth in
 * production: there is no DB read path, no LLM call on the request hot path,
 * no autonomous remote dependency. The dataset is auditable, deterministic,
 * and deploys with the image.
 *
 * CSV columns (header row required, in this order):
 * `word, language, length, frequency, difficulty, clue, source, source_license`.
 *
 * Rows are required to carry a non-blank `clue` — `export-words` never emits
 * empty clues, so an empty `clue` here means hand-edited corruption and
 * fails fast at parse time.
 */
class CsvWordRepository(
    words: List<Word>,
) : WordRepository {
    private val byLength: Map<Int, List<Word>> = words.groupBy { it.text.length }

    override fun findByLength(length: Int): List<Word> = byLength[length].orEmpty()

    override fun findByLengthAndPattern(
        length: Int,
        pattern: Map<Int, Char>,
    ): List<Word> =
        findByLength(length).filter { word ->
            pattern.all { (i, ch) -> i in word.text.indices && word.text[i] == ch }
        }

    companion object {
        private const val FRENCH_RESOURCE_PATH = "/words/words-fr.csv"

        private val REQUIRED_HEADERS =
            listOf("word", "language", "length", "frequency", "difficulty", "clue", "source", "source_license")

        /**
         * Loads the bundled French CSV corpus from the JVM classpath.
         *
         * Fails fast at startup if the file is missing, the header row is
         * malformed, or any row carries a blank `clue` (the API requires
         * one clue per word — `export-words` guarantees this invariant
         * on emit).
         */
        fun frenchFromClasspath(): CsvWordRepository = fromClasspath(FRENCH_RESOURCE_PATH)

        fun fromClasspath(path: String): CsvWordRepository {
            val stream =
                CsvWordRepository::class.java.getResourceAsStream(path)
                    ?: error("Word CSV not found on classpath: $path")
            return stream.use { input ->
                InputStreamReader(input, StandardCharsets.UTF_8).use { reader ->
                    // setHeader() with no args = auto-detect from the first CSV row,
                    // which we then validate against REQUIRED_HEADERS — this catches
                    // hand-edited corruption that reorders or renames columns.
                    val format =
                        CSVFormat.RFC4180
                            .builder()
                            .setHeader()
                            .setSkipHeaderRecord(true)
                            .build()
                    CSVParser.parse(reader, format).use { parser ->
                        validateHeader(parser.headerNames, path)
                        val words = parser.records.map { record -> toWord(record, path) }
                        CsvWordRepository(words)
                    }
                }
            }
        }

        private fun validateHeader(
            headers: List<String>,
            path: String,
        ) {
            require(headers == REQUIRED_HEADERS) {
                "CSV $path header mismatch — expected $REQUIRED_HEADERS, got $headers"
            }
        }

        private fun toWord(
            record: CSVRecord,
            path: String,
        ): Word {
            val text = record.get("word")
            val clue = record.get("clue")
            require(text.isNotBlank()) { "CSV $path row ${record.recordNumber}: empty word" }
            require(clue.isNotBlank()) {
                "CSV $path row ${record.recordNumber} ('$text'): empty clue (export-words guarantees non-null)"
            }
            return Word(text = text.uppercase(), definition = clue)
        }
    }
}
