/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/items/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the next unrated item for the caller.
         * @description Pulls one survey item the caller has not yet rated, applying tier-
         *     stratified weighted sampling and K-coverage prioritisation. Auth
         *     optional: signed-in callers are dedup'd server-side; anonymous
         *     callers may provide `excluded` to perform client-side dedup.
         */
        get: operations["getNextItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/items/{itemId}/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a rating for an item.
         * @description Server assigns `submittedAs` based on session presence. For auth
         *     callers, the partial unique index on (itemId, userId) makes this
         *     idempotent — a repeat submission returns 409 with the existing
         *     rating. For anon callers, every submit creates a new row (no
         *     server-side dedup). Anonymous callers including a `correctif` are
         *     rejected with 401.
         */
        post: operations["submitRating"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/items/pairs/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the next unrated pair (same mot) for pairwise rating.
         * @description Pulls two distinct survey items for the same `mot`, both unrated by
         *     the caller. Same auth/dedup rules as `/v1/items/next`. Returns 204
         *     when no mot has at least two unrated candidates available.
         */
        get: operations["getNextPair"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ratings/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a pairwise verdict on two items for the same mot.
         * @description Records a pairwise verdict. Routing depends on whether the verdict
         *     expresses a preference or a tied absolute judgment:
         *       - LEFT_WINS / RIGHT_WINS → 1 row in `pair_ratings` (consumed by
         *         DPO pair builder directly as chosen/rejected).
         *       - BOTH_GOOD → 2 rows in `ratings` (qualite=5 each).
         *       - BOTH_BAD  → 2 rows in `ratings` (qualite=1 each).
         *       - SKIP      → no writes; client advances.
         *     `pair_ratings` stays a strict preference table — every row is a
         *     usable DPO pair. Absolute judgments accumulate in `ratings`
         *     alongside the binary-mode submissions.
         */
        post: operations["submitPairRating"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Caller's rating progress. */
        get: operations["getMyProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/contributions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Caller's proposed-clue contributions. */
        get: operations["getMyContributions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update caller's survey preferences.
         * @description Currently only `deleteProposedOnErasure`. Updates `proposedBy.optedOut` for all existing contributions and applies to future ones.
         */
        patch: operations["patchMyPreferences"];
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness + readiness. */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Item: {
            /** Format: uuid */
            itemId: string;
            mot: string;
            definition: string;
            pos: components["schemas"]["Pos"];
            categorie: components["schemas"]["Categorie"];
            style: components["schemas"]["Style"];
            forceClaimed: number;
            longueur: number;
            /** @enum {string} */
            tier: "high" | "mid" | "low" | "excluded";
            isCalibration: boolean;
        };
        /** @enum {string} */
        Pos: "verbe_infinitif" | "verbe_conjugue" | "participe_passe" | "participe_present" | "nom_commun" | "nom_propre" | "adjectif" | "adverbe" | "interjection" | "mot_outil" | "sigle_abreviation" | "autre";
        /** @enum {string} */
        Categorie: "chemical_symbols" | "units" | "celestial_objects" | "nombres" | "roman_numerals" | "cardinal_points" | "cities" | "countries" | "country_codes" | "geography" | "first_names" | "titles" | "mythology" | "abbreviations" | "etranger" | "expressions" | "grammar" | "interjections" | "orthographe" | "animals" | "body_parts" | "senses" | "currencies" | "organizations" | "card_game" | "games" | "music_notes" | "autre" | "aliments" | "vetements" | "mobilier_objet" | "outils" | "transports" | "materiaux" | "professions" | "famille_relations" | "sentiments_etats" | "nature_paysage" | "flore" | "meteo_climat" | "temps_duree" | "couleurs" | "arts";
        /** @enum {string} */
        Style: "definition_directe" | "periphrase" | "metonymie" | "fonction_role" | "calembour" | "culturel" | "cryptique" | "cryptique_morphologique" | "technique";
        ItemPair: {
            mot: string;
            left: components["schemas"]["Item"];
            right: components["schemas"]["Item"];
        };
        /** @enum {string} */
        PairVerdict: "LEFT_WINS" | "RIGHT_WINS" | "BOTH_GOOD" | "BOTH_BAD" | "SKIP";
        PairRatingRequest: {
            /** Format: uuid */
            leftItemId: string;
            /** Format: uuid */
            rightItemId: string;
            verdict: components["schemas"]["PairVerdict"];
            difficulte: number;
            latencyMs: number;
        };
        RatingRequest: {
            qualite: number;
            difficulte: number;
            /** @enum {string} */
            flag?: "hors_sujet" | "auto_reference" | "erreur_sens" | "autre";
            /** @description Alternative clue text + claimed style. Authenticated callers only. */
            correctif?: {
                text: string;
                style: components["schemas"]["Style"];
            };
            latencyMs: number;
        };
        RatingResponse: {
            /** Format: uuid */
            ratingId: string;
            /** Format: uuid */
            itemId: string;
            /** @enum {string} */
            submittedAs: "auth" | "anon";
            /**
             * Format: uuid
             * @description UUID of the queued correctif item; null when no correctif was submitted.
             */
            proposedItemId: string | null;
        };
        CorrectifRejection: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            filterId: number;
            reason: string;
        };
        ProgressResponse: {
            itemsRated: number;
            /**
             * Format: float
             * @description Agreement ratio with calibration items; null until the first calibration rating.
             */
            calibrationAgreement: number | null;
            /**
             * Format: date-time
             * @description ISO-8601 timestamp of the most recent rating; null until the first submission.
             */
            lastRatedAt: string | null;
        };
        ContributionItem: {
            /** Format: uuid */
            itemId: string;
            mot: string;
            definition: string;
            pos: components["schemas"]["Pos"];
            categorie: components["schemas"]["Categorie"];
            style: components["schemas"]["Style"];
            optedOut: boolean;
            kCoverage: number;
            /** Format: date-time */
            createdAt: string;
        };
        PreferencesPatch: {
            deleteProposedOnErasure: boolean;
        };
        ProblemDetails: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail?: string;
        };
    };
    responses: {
        /** @description RFC 7807 problem details. */
        ProblemDetails: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getNextItem: {
        parameters: {
            query?: {
                /** @description Comma-separated list of `itemId`s the anonymous caller has already rated locally. Ignored when the caller is authenticated. */
                excluded?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Next item. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            /** @description Pool exhausted — no unrated items remain for this caller. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["ProblemDetails"];
        };
    };
    submitRating: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RatingRequest"];
            };
        };
        responses: {
            /** @description Rating accepted. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingResponse"];
                };
            };
            400: components["responses"]["ProblemDetails"];
            401: components["responses"]["ProblemDetails"];
            404: components["responses"]["ProblemDetails"];
            /** @description Auth caller already rated this item. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingResponse"];
                };
            };
            /** @description Correctif rejected by style-guide filters (1–7). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["CorrectifRejection"];
                };
            };
        };
    };
    getNextPair: {
        parameters: {
            query?: {
                /** @description Comma-separated list of `itemId`s the anonymous caller has already rated locally. Ignored when the caller is authenticated. */
                excluded?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Next pair. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemPair"];
                };
            };
            /** @description No mot has two unrated candidates available. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["ProblemDetails"];
        };
    };
    submitPairRating: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairRatingRequest"];
            };
        };
        responses: {
            /** @description Pair verdict recorded (or SKIP — no rows written). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ProblemDetails"];
            404: components["responses"]["ProblemDetails"];
            409: components["responses"]["ProblemDetails"];
        };
    };
    getMyProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Progress snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressResponse"];
                };
            };
            401: components["responses"]["ProblemDetails"];
        };
    };
    getMyContributions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of items the caller proposed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContributionItem"][];
                };
            };
            401: components["responses"]["ProblemDetails"];
        };
    };
    patchMyPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesPatch"];
            };
        };
        responses: {
            /** @description Preferences updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ProblemDetails"];
            401: components["responses"]["ProblemDetails"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Database or NATS unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
